import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ScannedFile } from './types.js';
import { L0IndexError } from '../errors/l0-index-error.js';

export interface ScannerOptions {
  ignorePatterns?: string[];
  followSymlinks?: boolean;
}

const DEFAULT_IGNORED_SEGMENTS = new Set([
  '.git',
  'node_modules',
]);

/**
 * Checks whether a relative path or segment should be excluded from L0 indexing.
 */
export function shouldIgnorePath(relativePath: string, customPatterns: string[] = []): boolean {
  const normalized = relativePath.replace(/\\/g, '/');
  const segments = normalized.split('/').filter(Boolean);

  // 1. Check default ignored segment names (e.g. .git, node_modules)
  for (const seg of segments) {
    if (DEFAULT_IGNORED_SEGMENTS.has(seg)) {
      return true;
    }
  }

  // 2. Ignore .ai-manager/cache and its contents (including context.db, context.db-wal, etc.)
  if (normalized === '.ai-manager/cache' || normalized.startsWith('.ai-manager/cache/')) {
    return true;
  }

  // 3. Ignore temporary and lock files generated by atomic writers, TypeScript, or SQLite
  const filename = path.basename(normalized);
  if (
    filename.includes('.tmp.') ||
    filename.endsWith('.tmp') ||
    filename.endsWith('.tsbuildinfo') ||
    filename.endsWith('.db-wal') ||
    filename.endsWith('.db-shm') ||
    filename.endsWith('.db-journal')
  ) {
    return true;
  }

  // 4. Custom patterns
  for (const pattern of customPatterns) {
    if (normalized === pattern || normalized.startsWith(pattern + '/') || filename === pattern) {
      return true;
    }
  }

  return false;
}

/**
 * Deterministically scans the filesystem rooted at workspaceRoot.
 * Returns sorted list of regular files with normalized relative paths.
 */
export async function scanWorkspaceFiles(
  workspaceRoot: string,
  options?: ScannerOptions
): Promise<ScannedFile[]> {
  const resolvedRoot = path.resolve(workspaceRoot);
  const discovered: ScannedFile[] = [];
  const visitedRealpaths = new Set<string>();

  try {
    const rootStat = await fs.promises.stat(resolvedRoot);
    if (!rootStat.isDirectory()) {
      throw new L0IndexError(`Workspace root is not a directory: '${resolvedRoot}'`, {
        operation: 'scanWorkspaceFiles',
        path: resolvedRoot,
      });
    }
    const realRoot = await fs.promises.realpath(resolvedRoot);
    visitedRealpaths.add(realRoot);
  } catch (err) {
    if (err instanceof L0IndexError) throw err;
    throw new L0IndexError(`Failed to access workspace root '${resolvedRoot}'`, {
      operation: 'scanWorkspaceFiles',
      path: resolvedRoot,
      cause: err,
    });
  }

  async function walk(currentDir: string): Promise<void> {
    let entries: fs.Dirent[];
    try {
      entries = await fs.promises.readdir(currentDir, { withFileTypes: true });
    } catch (err) {
      throw new L0IndexError(`Failed to read directory '${currentDir}'`, {
        operation: 'scanWorkspaceFiles',
        path: currentDir,
        cause: err,
      });
    }

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      const relativePath = path.relative(resolvedRoot, fullPath).replace(/\\/g, '/');

      if (shouldIgnorePath(relativePath, options?.ignorePatterns)) {
        continue;
      }

      if (entry.isDirectory()) {
        try {
          const real = await fs.promises.realpath(fullPath);
          if (visitedRealpaths.has(real)) {
            // Cycle or visited symlinked directory, skip
            continue;
          }
          visitedRealpaths.add(real);
          await walk(fullPath);
        } catch {
          // If realpath fails, skip inaccessible directory
          continue;
        }
      } else if (entry.isFile()) {
        try {
          const stat = await fs.promises.stat(fullPath);
          discovered.push({
            relativePath,
            fullPath,
            size: stat.size,
            mtimeMs: Math.round(stat.mtimeMs),
          });
        } catch {
          // Inaccessible or deleted file during walk, skip
          continue;
        }
      } else if (entry.isSymbolicLink()) {
        if (!options?.followSymlinks) {
          // By default do not traverse symlinks
          continue;
        }
        try {
          const stat = await fs.promises.stat(fullPath);
          if (stat.isDirectory()) {
            const real = await fs.promises.realpath(fullPath);
            if (!visitedRealpaths.has(real)) {
              visitedRealpaths.add(real);
              await walk(fullPath);
            }
          } else if (stat.isFile()) {
            discovered.push({
              relativePath,
              fullPath,
              size: stat.size,
              mtimeMs: Math.round(stat.mtimeMs),
            });
          }
        } catch {
          // Broken symlink, ignore safely
          continue;
        }
      }
    }
  }

  await walk(resolvedRoot);

  // Sort discovered relative paths lexicographically for deterministic traversal order
  discovered.sort((a, b) => (a.relativePath < b.relativePath ? -1 : a.relativePath > b.relativePath ? 1 : 0));

  return discovered;
}
